---
title: "MY459 Summative"
author: "Kobi Hackenburg"
date: "4/8/2021"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(quanteda, quietly = TRUE)
```

```{r}
#load clinton speeches
clinton <- "hillary2016primary.txt"
clinton <- paste0(readLines(clinton), collapse= " ")

#load sanders speeches
sanders <- "bernie2016primary.txt"
sanders <- paste0(readLines(sanders), collapse= " ")

#load trump speeches
trump <- "trump2016primary.txt"
trump <- paste0(readLines(trump), collapse= " ")

#load cruz speeches
cruz <- "cruz2016primary.txt"
cruz <- paste0(readLines(cruz), collapse= " ")

#create corpora
clinton_corpus <- corpus(clinton)
clinton_corpus <- `docnames<-`(clinton_corpus, "clinton")

sanders_corpus <- corpus(sanders)
sanders_corpus <- `docnames<-`(sanders_corpus, "sanders")

trump_corpus <- corpus(trump)
trump_corpus <- `docnames<-`(trump_corpus, "trump")

cruz_corpus <- corpus(cruz)
cruz_corpus <- `docnames<-`(cruz_corpus, "cruz")
```

```{r}
textstat_summary(clinton_corpus) #119,304 words & 7,251 types
textstat_summary(sanders_corpus) #91,155 words & 5,370 types
textstat_summary(trump_corpus) #145,087 words & 6,729 types
textstat_summary(cruz_corpus) #51,299 words & 5,060 types
```
```{r}
#load packages
library("word2vec")
library("tm")
library("pdftools")
library("stringr")

#preprocess corpus a bit more
clinton_corpus <- clinton_corpus %>% tolower() %>% removePunctuation() %>%
    removeNumbers()

sanders_corpus <- sanders_corpus %>% tolower() %>% removePunctuation() %>%
    removeNumbers()

trump_corpus <- trump_corpus %>% tolower() %>% removePunctuation() %>%
    removeNumbers()

cruz_corpus <- trump_corpus %>% tolower() %>% removePunctuation() %>%
    removeNumbers()

#convert to character vector
clinton.string <- as.character(clinton_corpus)
class(clinton.string)

sanders.string <- as.character(sanders_corpus)
class(sanders.string)

trump.string <- as.character(trump_corpus)
class(trump.string)

cruz.string <- as.character(cruz_corpus)
class(cruz.string)

#run word2vec model 
set.seed(1234)
word2vec_bernie <- word2vec(x = "bernie2016primary.txt", type = "skip-gram", dim = 300, window = 6, min_count = 4L)
word2vec_hillary <- word2vec(x = "hillary2016primary.txt", type = "skip-gram", dim = 300, window = 6, min_count = 4L)
word2vec_trump <- word2vec(x = "trump2016primary.txt", type = "skip-gram", dim = 300, window = 6,min_count = 4L)
word2vec_cruz <- word2vec(x = "cruz2016primary.txt", type = "skip-gram", dim = 300, window = 6,min_count = 4L)

#view embeddings 
embedding_bernie <- as.matrix(word2vec_bernie)
#head(embedding_bernie[,1:10])

embedding_hillary <- as.matrix(word2vec_hillary)
#head(embedding_hillary[,1:10])

embedding_trump <- as.matrix(word2vec_trump)
#head(embedding_trump[,1:10])

embedding_cruz <- as.matrix(word2vec_cruz)
#head(embedding_cruz[,1:10])

#see similar words 
predict(word2vec_bernie, newdata = c("america"), type = "nearest", top_n = 10)
predict(word2vec_hillary, newdata = c("america"), type = "nearest", top_n = 10)
predict(word2vec_trump, newdata = c("america"), type = "nearest", top_n = 10)
predict(word2vec_cruz, newdata = c("america"), type = "nearest", top_n = 10)

#get data frames of embeddings
data.embedding_bernie <- as.data.frame(embedding_bernie)
data.embedding_hillary <- as.data.frame(embedding_hillary)
data.embedding_trump <- as.data.frame(embedding_trump)
data.embedding_cruz <- as.data.frame(embedding_cruz)
```

```{r}
#extract vector for "America" for each candidate 
bernie_america_vector <- data.embedding_bernie[c("america"),]
bernie_america_vector <- as.vector(bernie_america_vector)

hillary_america_vector <- data.embedding_hillary[c("america"),]
hillary_america_vector <- as.vector(hillary_america_vector)

trump_america_vector <- data.embedding_trump[c("america"),]
trump_america_vector <- as.vector(trump_america_vector)

cruz_america_vector <- data.embedding_cruz[c("america"),]
cruz_america_vector <- as.vector(cruz_america_vector)

#write function to calculate cosine similarity  
CosineFun <- function(x, y){
  c <- sum(x*y) / (sqrt(sum(x * x)) * sqrt(sum(y * y)))
  return(c)
}
```


```{r}
#extract vectors for selected terms
  #bernie
bernie_proud_vector <- data.embedding_bernie[c("proud"),]
bernie_proud_vector <- as.vector(bernie_proud_vector)

bernie_strong_vector <- data.embedding_bernie[c("strong"),]
bernie_strong_vector <- as.vector(bernie_strong_vector)

bernie_great_vector <- data.embedding_bernie[c("great"),]
bernie_great_vector <- as.vector(bernie_great_vector)

bernie_safe_vector <- data.embedding_bernie[c("safe"),]
bernie_safe_vector <- as.vector(bernie_safe_vector)

bernie_opportunity_vector <- data.embedding_bernie[c("opportunity"),]
bernie_opportunity_vector <- as.vector(bernie_opportunity_vector)

bernie_promise_vector <- data.embedding_bernie[c("promise"),]
bernie_promise_vector <- as.vector(bernie_promise_vector)

bernie_hope_vector <- data.embedding_bernie[c("hope"),]
bernie_hope_vector <- as.vector(bernie_hope_vector)

bernie_important_vector <- data.embedding_bernie[c("important"),]
bernie_important_vector <- as.vector(bernie_important_vector)

bernie_honest_vector <- data.embedding_bernie[c("honest"),]
bernie_honest_vector <- as.vector(bernie_honest_vector)

bernie_fair_vector <- data.embedding_bernie[c("fair"),]
bernie_fair_vector <- as.vector(bernie_fair_vector)

bernie_together_vector <- data.embedding_bernie[c("together"),]
bernie_together_vector <- as.vector(bernie_together_vector)

bernie_united_vector <- data.embedding_bernie[c("united"),]
bernie_united_vector <- as.vector(bernie_united_vector)

bernie_community_vector <- data.embedding_bernie[c("community"),]
bernie_community_vector <- as.vector(bernie_community_vector)

bernie_hate_vector <- data.embedding_bernie[c("hate"),]
bernie_hate_vector <- as.vector(bernie_hate_vector)

bernie_honor_vector <- data.embedding_bernie[c("honor"),]
bernie_honor_vector <- as.vector(bernie_honor_vector)

bernie_good_vector <- data.embedding_bernie[c("good"),]
bernie_good_vector <- as.vector(bernie_good_vector)

bernie_change_vector <- data.embedding_bernie[c("change"),]
bernie_change_vector <- as.vector(bernie_change_vector)

bernie_individual_vector <- data.embedding_bernie[c("individual"),]
bernie_individual_vector <- as.vector(bernie_individual_vector)

#calculate cosine similarity between "America" and selected terms
bernie_amstrong <- CosineFun(bernie_strong_vector, bernie_america_vector)
bernie_amstrong
bernie_amsafe <- CosineFun(bernie_safe_vector, bernie_america_vector)
bernie_amsafe
bernie_amproud <- CosineFun(bernie_proud_vector, bernie_america_vector)
bernie_amproud
bernie_amgreat <- CosineFun(bernie_great_vector, bernie_america_vector)
bernie_amgreat
bernie_amopportunity <- CosineFun(bernie_opportunity_vector, bernie_america_vector)
bernie_amopportunity
bernie_ampromise <- CosineFun(bernie_promise_vector, bernie_america_vector)
bernie_ampromise
bernie_amhope <- CosineFun(bernie_hope_vector, bernie_america_vector)
bernie_amhope
bernie_amimportant <- CosineFun(bernie_important_vector, bernie_america_vector)
bernie_amimportant
bernie_amfair <- CosineFun(bernie_fair_vector, bernie_america_vector)
bernie_amfair
bernie_amunited <- CosineFun(bernie_united_vector, bernie_america_vector)
bernie_amunited
bernie_amhonor<- CosineFun(bernie_honor_vector, bernie_america_vector)
bernie_amhonor
bernie_amgood <- CosineFun(bernie_good_vector, bernie_america_vector)
bernie_amgood
bernie_amhate <- CosineFun(bernie_hate_vector, bernie_america_vector)
bernie_amhate
bernie_amchange <- CosineFun(bernie_change_vector, bernie_america_vector)
bernie_amchange
bernie_amindividual <- CosineFun(bernie_individual_vector, bernie_america_vector)
bernie_amindividual
bernie_amcommunity <- CosineFun(bernie_community_vector, bernie_america_vector)
bernie_amcommunity
bernie_amhonest <- CosineFun(bernie_honest_vector, bernie_america_vector)
bernie_amhonest
bernie_amtogether <- CosineFun(bernie_together_vector, bernie_america_vector)
bernie_amtogether
```


```{r}
#extract vectors for selected terms
  #hillary
hillary_proud_vector <- data.embedding_hillary[c("proud"),]
hillary_proud_vector <- as.vector(hillary_proud_vector)

hillary_strong_vector <- data.embedding_hillary[c("strong"),]
hillary_strong_vector <- as.vector(hillary_strong_vector)

hillary_great_vector <- data.embedding_hillary[c("great"),]
hillary_great_vector <- as.vector(hillary_great_vector)

hillary_safe_vector <- data.embedding_hillary[c("safe"),]
hillary_safe_vector <- as.vector(hillary_safe_vector)

hillary_opportunity_vector <- data.embedding_hillary[c("opportunity"),]
hillary_opportunity_vector <- as.vector(hillary_opportunity_vector)

hillary_promise_vector <- data.embedding_hillary[c("promise"),]
hillary_promise_vector <- as.vector(hillary_promise_vector)

hillary_hope_vector <- data.embedding_hillary[c("hope"),]
hillary_hope_vector <- as.vector(hillary_hope_vector)

hillary_important_vector <- data.embedding_hillary[c("important"),]
hillary_important_vector <- as.vector(hillary_important_vector)

hillary_honest_vector <- data.embedding_hillary[c("honest"),]
hillary_honest_vector <- as.vector(hillary_honest_vector)

hillary_fair_vector <- data.embedding_hillary[c("fair"),]
hillary_fair_vector <- as.vector(hillary_fair_vector)

hillary_together_vector <- data.embedding_hillary[c("together"),]
hillary_together_vector <- as.vector(hillary_together_vector)

hillary_united_vector <- data.embedding_hillary[c("united"),]
hillary_united_vector <- as.vector(hillary_united_vector)

hillary_community_vector <- data.embedding_hillary[c("community"),]
hillary_community_vector <- as.vector(hillary_community_vector)

hillary_hate_vector <- data.embedding_hillary[c("hate"),]
hillary_hate_vector <- as.vector(hillary_hate_vector)

hillary_honor_vector <- data.embedding_hillary[c("honor"),]
hillary_honor_vector <- as.vector(hillary_honor_vector)

hillary_good_vector <- data.embedding_hillary[c("good"),]
hillary_good_vector <- as.vector(hillary_good_vector)

hillary_change_vector <- data.embedding_hillary[c("change"),]
hillary_change_vector <- as.vector(hillary_change_vector)

hillary_individual_vector <- data.embedding_hillary[c("individual"),]
hillary_individual_vector <- as.vector(hillary_individual_vector)

#calculate cosine similarity between "America" and selected terms
hillary_amstrong <- CosineFun(hillary_strong_vector, hillary_america_vector)
hillary_amstrong
hillary_amsafe <- CosineFun(hillary_safe_vector, hillary_america_vector)
hillary_amsafe
hillary_amproud <- CosineFun(hillary_proud_vector, hillary_america_vector)
hillary_amproud
hillary_amgreat <- CosineFun(hillary_great_vector, hillary_america_vector)
hillary_amgreat
hillary_amopportunity <- CosineFun(hillary_opportunity_vector, hillary_america_vector)
hillary_amopportunity
hillary_ampromise <- CosineFun(hillary_promise_vector, hillary_america_vector)
hillary_ampromise
hillary_amhope <- CosineFun(hillary_hope_vector, hillary_america_vector)
hillary_amhope
hillary_amimportant <- CosineFun(hillary_important_vector, hillary_america_vector)
hillary_amimportant
hillary_amfair <- CosineFun(hillary_fair_vector, hillary_america_vector)
hillary_amfair
hillary_amunited <- CosineFun(hillary_united_vector, hillary_america_vector)
hillary_amunited
hillary_amhonor<- CosineFun(hillary_honor_vector, hillary_america_vector)
hillary_amhonor
hillary_amgood <- CosineFun(hillary_good_vector, hillary_america_vector)
hillary_amgood
hillary_amhate <- CosineFun(hillary_hate_vector, hillary_america_vector)
hillary_amhate
hillary_amchange <- CosineFun(hillary_change_vector, hillary_america_vector)
hillary_amchange
hillary_amindividual <- CosineFun(hillary_individual_vector, hillary_america_vector)
hillary_amindividual
hillary_amcommunity <- CosineFun(hillary_community_vector, hillary_america_vector)
hillary_amcommunity
hillary_amhonest <- CosineFun(hillary_honest_vector, hillary_america_vector)
hillary_amhonest
hillary_amtogether <- CosineFun(hillary_together_vector, hillary_america_vector)
hillary_amtogether
```


```{r}
#trump
trump_proud_vector <- data.embedding_trump[c("proud"),]
trump_proud_vector <- as.vector(trump_proud_vector)

trump_strong_vector <- data.embedding_trump[c("strong"),]
trump_strong_vector <- as.vector(trump_strong_vector)

trump_great_vector <- data.embedding_trump[c("great"),]
trump_great_vector <- as.vector(trump_great_vector)

trump_safe_vector <- data.embedding_bernie[c("safe"),]
trump_safe_vector <- as.vector(trump_safe_vector)

trump_opportunity_vector <- data.embedding_trump[c("opportunity"),]
trump_opportunity_vector <- as.vector(trump_opportunity_vector)

trump_promise_vector <- data.embedding_trump[c("promise"),]
trump_promise_vector <- as.vector(trump_promise_vector)

trump_hope_vector <- data.embedding_trump[c("hope"),]
trump_hope_vector <- as.vector(trump_hope_vector)

trump_important_vector <- data.embedding_trump[c("important"),]
trump_important_vector <- as.vector(trump_important_vector)

trump_honest_vector <- data.embedding_trump[c("honest"),]
trump_honest_vector <- as.vector(trump_honest_vector)

trump_fair_vector <- data.embedding_trump[c("fair"),]
trump_fair_vector <- as.vector(trump_fair_vector)

trump_together_vector <- data.embedding_trump[c("together"),]
trump_together_vector <- as.vector(trump_together_vector)

trump_united_vector <- data.embedding_trump[c("united"),]
trump_united_vector <- as.vector(trump_united_vector)

trump_community_vector <- data.embedding_trump[c("community"),]
trump_community_vector <- as.vector(trump_community_vector)

trump_hate_vector <- data.embedding_trump[c("hate"),]
trump_hate_vector <- as.vector(trump_hate_vector)

trump_honor_vector <- data.embedding_trump[c("honor"),]
trump_honor_vector <- as.vector(trump_honor_vector)

trump_good_vector <- data.embedding_trump[c("good"),]
trump_good_vector <- as.vector(trump_good_vector)

trump_change_vector <- data.embedding_trump[c("change"),]
trump_change_vector <- as.vector(trump_change_vector)

trump_individual_vector <- data.embedding_trump[c("individual"),]
trump_individual_vector <- as.vector(trump_individual_vector)

#calculate cosine similarity between "America" and selected terms
trump_amstrong <- CosineFun(trump_strong_vector, trump_america_vector)
trump_amstrong
trump_amsafe <- CosineFun(trump_safe_vector, trump_america_vector)
trump_amsafe
trump_amproud <- CosineFun(trump_proud_vector, trump_america_vector)
trump_amproud
trump_amgreat <- CosineFun(trump_great_vector, trump_america_vector)
trump_amgreat
trump_amopportunity <- CosineFun(trump_opportunity_vector, trump_america_vector)
trump_amopportunity
trump_ampromise <- CosineFun(trump_promise_vector, trump_america_vector)
trump_ampromise
trump_amhope <- CosineFun(trump_hope_vector, trump_america_vector)
trump_amhope
trump_amimportant <- CosineFun(trump_important_vector, trump_america_vector)
trump_amimportant
trump_amfair <- CosineFun(trump_fair_vector, trump_america_vector)
trump_amfair
trump_amunited <- CosineFun(trump_united_vector, trump_america_vector)
trump_amunited
trump_amhonor<- CosineFun(trump_honor_vector, trump_america_vector)
trump_amhonor
trump_amgood <- CosineFun(trump_good_vector, trump_america_vector)
trump_amgood
trump_amhate <- CosineFun(trump_hate_vector, trump_america_vector)
trump_amhate
trump_amchange <- CosineFun(trump_change_vector, trump_america_vector)
trump_amchange
trump_amindividual <- CosineFun(trump_individual_vector, trump_america_vector)
trump_amindividual
trump_amcommunity <- CosineFun(trump_community_vector, trump_america_vector)
trump_amcommunity
trump_amhonest <- CosineFun(trump_honest_vector, trump_america_vector)
trump_amhonest
trump_amtogether <- CosineFun(trump_together_vector, trump_america_vector)
trump_amtogether
```


```{r}
#extract vectors for selected terms
  #cruz
cruz_proud_vector <- data.embedding_cruz[c("proud"),]
cruz_proud_vector <- as.vector(cruz_proud_vector)

cruz_strong_vector <- data.embedding_cruz[c("strong"),]
cruz_strong_vector <- as.vector(cruz_strong_vector)

cruz_great_vector <- data.embedding_cruz[c("great"),]
cruz_great_vector <- as.vector(cruz_great_vector)

cruz_safe_vector <- data.embedding_cruz[c("safe"),]
cruz_safe_vector <- as.vector(cruz_safe_vector)

cruz_opportunity_vector <- data.embedding_cruz[c("opportunity"),]
cruz_opportunity_vector <- as.vector(cruz_opportunity_vector)

cruz_promise_vector <- data.embedding_cruz[c("promise"),]
cruz_promise_vector <- as.vector(cruz_promise_vector)

cruz_hope_vector <- data.embedding_cruz[c("hope"),]
cruz_hope_vector <- as.vector(cruz_hope_vector)

cruz_important_vector <- data.embedding_cruz[c("important"),]
cruz_important_vector <- as.vector(cruz_important_vector)

cruz_honest_vector <- data.embedding_cruz[c("honest"),]
cruz_honest_vector <- as.vector(cruz_honest_vector)

cruz_fair_vector <- data.embedding_cruz[c("fair"),]
cruz_fair_vector <- as.vector(cruz_fair_vector)

cruz_together_vector <- data.embedding_cruz[c("together"),]
cruz_together_vector <- as.vector(cruz_together_vector)

cruz_united_vector <- data.embedding_cruz[c("united"),]
cruz_united_vector <- as.vector(cruz_united_vector)

cruz_community_vector <- data.embedding_cruz[c("community"),]
cruz_community_vector <- as.vector(cruz_community_vector)

cruz_hate_vector <- data.embedding_cruz[c("hate"),]
cruz_hate_vector <- as.vector(cruz_hate_vector)

cruz_honor_vector <- data.embedding_cruz[c("honor"),]
cruz_honor_vector <- as.vector(cruz_honor_vector)

cruz_good_vector <- data.embedding_cruz[c("good"),]
cruz_good_vector <- as.vector(cruz_good_vector)

cruz_change_vector <- data.embedding_cruz[c("change"),]
cruz_change_vector <- as.vector(cruz_change_vector)

cruz_individual_vector <- data.embedding_cruz[c("individual"),]
cruz_individual_vector <- as.vector(cruz_individual_vector)

#calculate cosine similarity between "America" and selected terms
cruz_amstrong <- CosineFun(cruz_strong_vector, cruz_america_vector)
cruz_amstrong
cruz_amsafe <- CosineFun(cruz_safe_vector, cruz_america_vector)
cruz_amsafe
cruz_amproud <- CosineFun(cruz_proud_vector, cruz_america_vector)
cruz_amproud
cruz_amgreat <- CosineFun(cruz_great_vector, cruz_america_vector)
cruz_amgreat
cruz_amopportunity <- CosineFun(cruz_opportunity_vector, cruz_america_vector)
cruz_amopportunity
cruz_ampromise <- CosineFun(cruz_promise_vector, cruz_america_vector)
cruz_ampromise
cruz_amhope <- CosineFun(cruz_hope_vector, cruz_america_vector)
cruz_amhope
cruz_amimportant <- CosineFun(cruz_important_vector, cruz_america_vector)
cruz_amimportant
cruz_amfair <- CosineFun(cruz_fair_vector, cruz_america_vector)
cruz_amfair
cruz_amunited <- CosineFun(cruz_united_vector, cruz_america_vector)
cruz_amunited
cruz_amhonor<- CosineFun(cruz_honor_vector, cruz_america_vector)
cruz_amhonor
cruz_amgood <- CosineFun(cruz_good_vector, cruz_america_vector)
cruz_amgood
cruz_amhate <- CosineFun(cruz_hate_vector, cruz_america_vector)
cruz_amhate
cruz_amchange <- CosineFun(cruz_change_vector, cruz_america_vector)
cruz_amchange
cruz_amindividual <- CosineFun(cruz_individual_vector, cruz_america_vector)
cruz_amindividual
cruz_amcommunity <- CosineFun(cruz_community_vector, cruz_america_vector)
cruz_amcommunity
cruz_amhonest <- CosineFun(cruz_honest_vector, cruz_america_vector)
cruz_amhonest
cruz_amtogether <- CosineFun(cruz_together_vector, cruz_america_vector)
cruz_amtogether
```

```{r}
#load packages
library(quanteda.dictionaries)

#create dfm
clinton_dfm <- dfm(clinton_corpus, remove = stopwords("en"), remove_punct=TRUE, remove_numbers=TRUE, stem = FALSE, verbose = FALSE)

sanders_dfm <- dfm(sanders_corpus, remove = stopwords("en"), remove_punct=TRUE, remove_numbers=TRUE, stem = FALSE, verbose = FALSE)

trump_dfm <- dfm(trump_corpus, remove = stopwords("en"), remove_punct=TRUE, remove_numbers=TRUE, stem = FALSE, verbose = FALSE)

cruz_dfm <- dfm(cruz_corpus, remove = stopwords("en"), remove_punct=TRUE, remove_numbers=TRUE, stem = FALSE, verbose = FALSE)

clinton_dfm <-dfm_weight(clinton_dfm, scheme = "prop")

textstat_lexdiv(cruz_dfm)

#apply MFD
dict_moral_clinton <- dfm_lookup(clinton_dfm, dictionary = data_dictionary_MFD, verbose = FALSE)
data_moral_clinton <- as.data.frame(dict_moral_clinton)

dict_moral_sanders <- dfm_lookup(sanders_dfm, dictionary = data_dictionary_MFD, verbose = FALSE)
data_moral_sanders <- as.data.frame(dict_moral_sanders)

dict_moral_trump <- dfm_lookup(trump_dfm, dictionary = data_dictionary_MFD, verbose = FALSE)
data_moral_trump <- as.data.frame(dict_moral_trump)

dict_moral_cruz <- dfm_lookup(cruz_dfm, dictionary = data_dictionary_MFD, verbose = FALSE)
data_moral_cruz <- as.data.frame(dict_moral_cruz)

#see clinton scores for virtues 
data_moral_clinton$care.virtue #860
data_moral_clinton$fairness.virtue #304
data_moral_clinton$loyalty.virtue #1299
data_moral_clinton$authority.virtue #750
data_moral_clinton$sanctity.virtue #136

#see sanders scores for virtues 
data_moral_sanders$care.virtue #585
data_moral_sanders$fairness.virtue #262
data_moral_sanders$loyalty.virtue #1421
data_moral_sanders$authority.virtue #449
data_moral_sanders$sanctity.virtue #113

#see trump scores for virtues 
data_moral_trump$care.virtue #772
data_moral_trump$fairness.virtue #319
data_moral_trump$loyalty.virtue #1677
data_moral_trump$authority.virtue #968
data_moral_trump$sanctity.virtue #187

#see cruz scores for virtues 
data_moral_cruz$care.virtue #207
data_moral_cruz$fairness.virtue #184
data_moral_cruz$loyalty.virtue #524
data_moral_cruz$authority.virtue #484
data_moral_cruz$sanctity.virtue #395

#seeing full list of terms in each category
xxx<- (data_dictionary_MFD)
```

```{r}
#plot word embeddings side-by-side for clinton and sanders 
library(keras)
library(text2vec)
library(uwot)
library(dplyr)
library(ggplot2)

# Word2Vec dimension reduction
bernie_umap <- umap(embedding_bernie, n_components = 2, metric = "cosine", n_neighbors = 25, min_dist = 0.1, spread=2)

hillary_umap <- umap(embedding_hillary, n_components = 2, metric = "cosine", n_neighbors = 25, min_dist = 0.1, spread=2)

trump_umap <- umap(embedding_trump, n_components = 2, metric = "cosine", n_neighbors = 25, min_dist = 0.1, spread=2)

cruz_umap <- umap(embedding_cruz, n_components = 2, metric = "cosine", n_neighbors = 25, min_dist = 0.1, spread=2)

# Dimensions of end result
dim(hillary_umap)

# Put results in a dataframe for ggplot and add labels
  #hillary
df_hillary_umap <- as.data.frame(hillary_umap, stringsAsFactors = FALSE)
df_hillary_umap$word <- rownames(embedding_hillary)
colnames(df_hillary_umap) <- c("UMAP1", "UMAP2", "word")
df_hillary_umap$technique <- 'Hillary Clinton'
cat(paste0('Clinton embeddings reduced to 2 dimensions:', '\n'))
str(df_hillary_umap)

  #bernie
df_bernie_umap <- as.data.frame(bernie_umap, stringsAsFactors = FALSE)
df_bernie_umap$word <- rownames(embedding_bernie)
colnames(df_bernie_umap) <- c("UMAP1", "UMAP2", "word")
df_bernie_umap$technique <- 'Bernie Sanders'
cat(paste0('\n', 'Sanders embeddings reduced to 2 dimensions:', '\n'))
str(df_bernie_umap)

   #trump
df_trump_umap <- as.data.frame(trump_umap, stringsAsFactors = FALSE)
df_trump_umap$word <- rownames(embedding_trump)
colnames(df_trump_umap) <- c("UMAP1", "UMAP2", "word")
df_trump_umap$technique <- 'Donald Trump'
cat(paste0('\n', 'Trump embeddings reduced to 2 dimensions:', '\n'))
str(df_trump_umap)

  #cruz
df_cruz_umap <- as.data.frame(cruz_umap, stringsAsFactors = FALSE)
df_cruz_umap$word <- rownames(embedding_cruz)
colnames(df_cruz_umap) <- c("UMAP1", "UMAP2", "word")
df_cruz_umap$technique <- 'Ted Cruz'
cat(paste0('\n', 'Cruz embeddings reduced to 2 dimensions:', '\n'))
str(df_cruz_umap)

# Combine the datasets
#df_umap <- bind_rows(df_hillary_umap, df_bernie_umap)
df_umap <- bind_rows(df_hillary_umap, df_bernie_umap, df_trump_umap, df_cruz_umap)

# Plot the UMAP dimensions for both Hillary and Bernie
ggplot(df_umap) +
      geom_point(aes(x = UMAP1, y = UMAP2), colour = 'navyblue', size = 0.05) +
      facet_wrap(~technique) +
      labs(title = "Word Embeddings for 2016 U.S. Presidential Candidates using UMAP Dimension Reduction") +
      theme(plot.title = element_text(hjust = .5, size = 10, face = "bold"))
```
```{r}
library(ggrepel)
#'america' for the Bernie model
tokenx <- "america"
embedding_vectorx <- t(matrix(embedding_bernie[tokenx,])) 
cos_sim = sim2(x = embedding_bernie, y = embedding_vectorx, method = "cosine", norm = "l2")
selectx <- data.frame(rownames(as.data.frame(head(sort(cos_sim[,1], decreasing = TRUE), 5))))
colnames(selectx) <- "word"
selected_wordsx <- df_bernie_umap %>% inner_join(y=selectx, by= "word", match = "all") 

america_bernie <- ggplot(selected_wordsx, aes(x = UMAP1, y = UMAP2, colour = word == 'america')) + 
      geom_point(show.legend = FALSE) + 
      scale_color_manual(values = c('black', 'red')) +
      geom_text_repel(aes(UMAP1, UMAP2, label = word), show.legend = FALSE, size = 2.5, vjust=0, hjust=0) +
      labs(title = "Bernie Sanders") +
      theme(plot.title = element_text(hjust = 0, size = 14))


#'America' for the Hillary model
tokeny <- "america"
embedding_vectory <- t(matrix(embedding_hillary[tokeny,])) 
cos_sim = sim2(x = embedding_hillary, y = embedding_vectory, method = "cosine", norm = "l2")
selecty <- data.frame(rownames(as.data.frame(head(sort(cos_sim[,1], decreasing = TRUE), 5))))
colnames(selecty) <- "word"
selected_wordsy <- df_hillary_umap %>% inner_join(y=selecty, by= "word", match = "all") 

america_hillary <- ggplot(selected_wordsy, aes(x = UMAP1, y = UMAP2, colour = word == 'america')) + 
      geom_point(show.legend = FALSE) + 
      scale_color_manual(values = c('black', 'red')) +
      geom_text_repel(aes(UMAP1, UMAP2, label = word), show.legend = FALSE, size = 2.5, vjust=0, hjust=0) +
      labs(title = "Hillary Clinton") +
      theme(plot.title = element_text(hjust = 0, size = 14))


#'America' for the Trump model
tokenz <- "america"
embedding_vectorz <- t(matrix(embedding_trump[tokenz,])) 
cos_sim = sim2(x = embedding_trump, y = embedding_vectorz, method = "cosine", norm = "l2")
selectz <- data.frame(rownames(as.data.frame(head(sort(cos_sim[,1], decreasing = TRUE), 5))))
colnames(selectz) <- "word"
selected_wordsz <- df_trump_umap %>% inner_join(y=selectz, by= "word", match = "all") 

america_trump <- ggplot(selected_wordsz, aes(x = UMAP1, y = UMAP2, colour = word == 'america')) + 
      geom_point(show.legend = FALSE) + 
      scale_color_manual(values = c('black', 'red')) +
      geom_text_repel(aes(UMAP1, UMAP2, label = word), show.legend = FALSE, size = 2.5, vjust=0, hjust=0) +
      labs(title = "Donald Trump") +
      theme(plot.title = element_text(hjust = 0, size = 14))


#'America' for the Cruz model
tokenw <- "america"
embedding_vectorw <- t(matrix(embedding_cruz[tokenw,])) 
cos_sim = sim2(x = embedding_cruz, y = embedding_vectorw, method = "cosine", norm = "l2")
selectw <- data.frame(rownames(as.data.frame(head(sort(cos_sim[,1], decreasing = TRUE), 5))))
colnames(selectw) <- "word"
selected_wordsw <- df_cruz_umap %>% inner_join(y=selectw, by= "word", match = "all") 

america_cruz <- ggplot(selected_wordsw, aes(x = UMAP1, y = UMAP2, colour = word == 'america')) + 
      geom_point(show.legend = FALSE) + 
      scale_color_manual(values = c('black', 'red')) +
      geom_text_repel(aes(UMAP1, UMAP2, label = word), show.legend = FALSE, size = 2.5, vjust=0, hjust=0) +
      labs(title = "Ted Cruz") +
      theme(plot.title = element_text(hjust = 0, size = 14))

#href
# Plot the results for each candidate side-by-side for comparison
library(gridExtra)
grid.arrange(america_trump, america_cruz, america_hillary, america_bernie, ncol=2)
```
